[project]
name = "python-server-machine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydot>=4.0.1",
    "python-statemachine==2.5.0",
]
