first:
  - Alucard
  - Ambrose
  - Ash
  - Bellamy
  - Calder
  - Calypso
  - Chartreuse
  - Clover
  - Dahlia
  - Darrow
  - Deacon
  - Elowen
  - Emrys
  - Fable
  - Fiorella
  - Flynn
  - Gatlin
  - Gerard
  - Hadron
  - Harlow
  - Indigo
  - Isla
  - Jaden
  - Kai
  - Kismet
  - Leo
  - Mika
  - Moon
  - Nyx
  - Orna
  - Phaedra
  - Quill
  - Rani
  - Raphael
  - Reza
  - Roux
  - Saffron
  - Sierra
  - Skye
  - Talon
  - Thea
  - Triton
  - Vala
  - Velo
  - Wisteria
  - Yanelle
  - Zahara
last:
  - Abbot
  - Advani
  - Agoston
  - Baptiste
  - Belgarde
  - Blossom
  - Chance
  - Covault
  - Dawn
  - Dennison
  - Drayer
  - Emrick
  - Foley
  - Fury
  - Grove
  - Hartley
  - Humfleet
  - Hyland
  - Ikeda
  - Jones
  - Jordon
  - Kaan
  - Knoth
  - Lagrange
  - Lockamy
  - Lyon
  - Marche
  - Merrell
  - Newland
  - Novak
  - Orwick
  - Overholt
  - Pray
  - Rathbone
  - Rose
  - Seagrave
  - Spurlock
  - Thorn
  - Tringle
  - Vasquez
  - Warren
  - Worth
  - York
